# Use the official Python image
FROM python:3.10-slim
WORKDIR /app

# Copy the application
COPY . .

# Install Python dependencies  
# RUN pip install -r requirements.txt

# Run the Python application
CMD ["python3", "challenge.py", "../artefakter"]
